# Device
device: 'cuda'

# Model parameters
model:
  cell: 'LTCCell'
  in_features: 4
  hidden_features: 128
  out_features: 1
  backbone_features: 64
  backbone_depth: 4

# Training parameters
train:
  epochs: 100
  batch_size: 16
  seq_len: 128
  lr: 0.001
  tau: 0.001
